### ISSUE TITLE
Download all the package information from all configured sources.

### ISSUE THREAD

**Issue by ShubhamGupta1995** [geerlingguy/ansible-role-haproxy#42]
I was using the **haproxy** role and when I ran the playbook it throws me an error 

> Install haproxy failed

I executed the command first `sudo apt update` and then `ansible-playbook <my-haproxyplaybook.yml>` and it worked. This is not the major thing but if anyone configuring a new server it helps. So, only need to add the command module in your role `<package-manager> update` .

**Comment by geerlingguy** [comment]
@ShubhamGupta1995 - Typically I recommend people add an apt `update_cache: yes` task in their playbook before calling any roles if running on Ubuntu/Debian. That way your playbook has control over the apt cache management.

**Comment by ShubhamGupta1995** [comment]
> @ShubhamGupta1995 - Typically I recommend people add an apt `update_cache: yes` task in their playbook before calling any roles if running on Ubuntu/Debian. That way your playbook has control over the apt-cache management.

Thanks @geerlingguy for your reply. Is `update_cache: yes` is similar to `apt update`?

**Comment by geerlingguy** [comment]
Basically, add a section like this one near the top of your playbook: https://github.com/geerlingguy/ansible-role-haproxy/blob/master/molecule/default/converge.yml#L16-L19
